language: php
php:
- 5.6
- 5.5
addons:
  postgresql: '9.4'
install:
- pecl install PDO_PGSQL
- composer install
env:
  global:
  - APP_ENV=testing
  - DB_CONNECTION=pgsql
  - DATABASE_URL=postgres:///
before_script:
- psql -c 'create database recordings_test;' -U postgres
- php artisan migrate
