language: php
php:
- 5.6
- 5.5
addons:
  postgresql: '9.4'
install:
- pecl install PDO_PGSQL
- composer install
scripts:
  - mkdir -p build/logs
env:
  global:
  - APP_ENV=testing
  - DB_CONNECTION=pgsql
  - DB_HOST=localhost
  - DB_NAME=recording_test
  - DB_USERNAME=postgres
before_script:
- psql -c 'create database recording_test;' -U postgres
- php artisan migrate
